-- MySQL Script generated by MySQL Workbench
-- Sun Feb 28 14:50:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinicaveterinaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicaveterinaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicaveterinaria` DEFAULT CHARACTER SET utf8 ;
USE `clinicaveterinaria` ;

-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`cliente` (
  `cpf` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(25) NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`animal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `sexo` ENUM('m', 'f') NOT NULL,
  `nascimento` DATE NOT NULL,
  `especie` VARCHAR(25) NOT NULL,
  `raca` VARCHAR(25) NULL,
  `peso` FLOAT NOT NULL,
  `dono_cpf` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idAnimal_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `donocpf_idx` (`dono_cpf` ASC) VISIBLE,
  CONSTRAINT `donocpf`
    FOREIGN KEY (`dono_cpf`)
    REFERENCES `clinicaveterinaria`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`veterinario` (
  `cpf` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(25) NULL,
  `especialidade` VARCHAR(25) NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`servico` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(25) NOT NULL,
  `valor` FLOAT UNSIGNED NOT NULL,
  `data` DATE NULL,
  `veterinario_cpf` INT UNSIGNED NOT NULL,
  `cliente_cpf` INT UNSIGNED NOT NULL,
  `animal_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idservico_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `veterinario_cpf_idx` (`veterinario_cpf` ASC) VISIBLE,
  INDEX `cliente_cpf_idx` (`cliente_cpf` ASC) VISIBLE,
  INDEX `animal_id_idx` (`animal_id` ASC) VISIBLE,
  CONSTRAINT `veterinario_cpf`
    FOREIGN KEY (`veterinario_cpf`)
    REFERENCES `clinicaveterinaria`.`veterinario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_cpf`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `clinicaveterinaria`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animal_id`
    FOREIGN KEY (`animal_id`)
    REFERENCES `clinicaveterinaria`.`animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`funcionario` (
  `cpf` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(25) NULL,
  `funcao` VARCHAR(25) NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
