-- MySQL Script generated by MySQL Workbench
-- Tue Mar  9 09:57:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinicaveterinaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicaveterinaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicaveterinaria` DEFAULT CHARACTER SET utf8 ;
USE `clinicaveterinaria` ;

-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`animal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `sexo` ENUM('m', 'f') NOT NULL,
  `nascimento` DATE NOT NULL,
  `especie` VARCHAR(25) NOT NULL,
  `raca` VARCHAR(25) NULL,
  `peso` FLOAT NOT NULL,
  `dono_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `dono_id_idx` (`dono_id` ASC) INVISIBLE,
  CONSTRAINT `dono_id`
    FOREIGN KEY (`dono_id`)
    REFERENCES `clinicaveterinaria`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`veterinario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(25) NULL,
  `senha` VARCHAR(255) NOT NULL,
  `especialidade` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`servico` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(25) NOT NULL,
  `valor` FLOAT UNSIGNED NOT NULL,
  `data` DATE NULL,
  `veterinario_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `animal_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `veterinario_id_idx` (`veterinario_id` ASC) VISIBLE,
  INDEX `cliente_id_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `animal_id_idx` (`animal_id` ASC) VISIBLE,
  CONSTRAINT `veterinario_id`
    FOREIGN KEY (`veterinario_id`)
    REFERENCES `clinicaveterinaria`.`veterinario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `clinicaveterinaria`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animal_id`
    FOREIGN KEY (`animal_id`)
    REFERENCES `clinicaveterinaria`.`animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaveterinaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaveterinaria`.`funcionario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `sexo` ENUM('m', 'f') NULL,
  `nascimento` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(25) NULL,
  `senha` VARCHAR(255) NOT NULL,
  `funcao` VARCHAR(25) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
